### ISSUE TITLE
I am using this viewever to get the point cloud of Kinect data..I am not getting the points

### ISSUE THREAD

**Issue by chandanlal92** [dirkholz/pcl_online_viewer#1]
Hi,
I am using this viewer to get point cloud data from kinect sensor.I am able to get the point cloud view but I am getting following issue so that I am not able to get the point cloud data.

vtkOpenGLPolyDataMapper (0x2abcf20): failed after UpdateShader 1 OpenGL errors detected

**Comment by christianlandgraf** [comment]
Hey, when trying this package I get the same error. Did you find a solution?

**Comment by chandanlal92** [comment]
I dont remember the solution. But I will add worked method. I guess giving delay or memory lock helped. Here is the working method:

boost::shared_ptr<pcl::visualization::PCLVisualizer> normalsVis (
pcl::PointCloud<pcl::PointXYZ>::ConstPtr cloud, pcl::PointCloud<pcl::Normal>::ConstPtr normals, pcl::PointXYZ center, Eigen::Matrix3f matrix_1)
{
// --------------------------------------------------------
// -----Open 3D viewer and add point cloud and normals-----
// --------------------------------------------------------
m.lock();
//~ pcl::visualization::PointCloudColorHandler<pcl::PCLPointCloud2> ColorHandler;

/*
 * Defining Point Cloud Viewer Parameters
 * 
 * */
boost::shared_ptr<pcl::visualization::PCLVisualizer> viewer (new pcl::visualization::PCLVisualizer ("3D Viewer"));

//~ viewer->spinOnce (10);

//~ cout<< ("PointCloud with %d data points (%s)  and frame %s.",
//~ cloud->width * cloud->height,
//~ pcl::getFieldsList (*cloud).c_str (),
//~ cloud->header.frame_id.c_str ());   
//~ color_handler.reset (new pcl::visualization::PointCloudColorHandlerCustom<pcl::PCLPointCloud2>(cloud, "rgb" ));            
viewer->setBackgroundColor (0, 0, 0);
viewer->addPointCloud<pcl::PointXYZ> (cloud,"sample cloud");
viewer->setPointCloudRenderingProperties (pcl::visualization::PCL_VISUALIZER_POINT_SIZE, 3, "sample cloud");
//~ viewer->addPointCloudNormals<pcl::PointXYZ, pcl::Normal> (cloud, normals, 10, 0.1, "normals");
//~ viewer->setPointCloudRenderingProperties (pcl::visualization::PCL_VISUALIZER_LINE_WIDTH, 4, "normals");
//~ viewer->setPointCloudRenderingProperties (pcl::visualization::PCL_VISUALIZER_COLOR, 0.0, 1.0, 0.0, "normals"); 



pcl::PointXYZ center_0 (center.x,center.y,center.z);

/*
 * Defining X,Y,Z Axis in the From the Vector Form 
 * 
 * */


pcl::PointXYZ x_axis (matrix_1(0,0), matrix_1(0,1), matrix_1(0,2));
pcl::PointXYZ y_axis (matrix_1(1,0), matrix_1(1,1), matrix_1(1,2));
pcl::PointXYZ z_axis (matrix_1(2,0), matrix_1(2,1), matrix_1(2,2));
 
viewer->addLine (center_0, x_axis, 1.0f, 0.0f, 0.0f, "major eigen vector"+1);
viewer->addLine (center_0, y_axis, 0.0f, 1.0f, 0.0f, "middle eigen vector3"+4);
viewer->addLine (center_0, z_axis, 0.0f, 0.0f, 1.0f, "minor eigen vector6"+7);
viewer->addCoordinateSystem (0.5);
//~ viewer->initCameraParameters ();
while(!viewer->wasStopped())
{
viewer->spinOnce (100);
boost::this_thread::sleep (boost::posix_time::microseconds (100000));
}
//~ return(viewer);
m.unlock();
}

**Comment by chandanlal92** [comment]
I think this part was the solution. Not sure its been a while since I worked on this:

while(!viewer->wasStopped())
{
viewer->spinOnce (100);
boost::this_thread::sleep (boost::posix_time::microseconds (100000));
}
